# Generated by Django 3.2.6 on 2021-08-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('mbti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.mbti')),
            ],
        ),
    ]
