# Generated by Django 3.2.6 on 2021-08-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('mbti_id', models.BigAutoField(help_text='mbti ID', primary_key=True, serialize=False)),
                ('mbti', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(help_text='school ID', primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(help_text='school ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(default='21학번', max_length=4)),
                ('mbti', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.mbti')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school')),
            ],
        ),
    ]
