# Generated by Django 3.2.6 on 2021-08-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.PositiveIntegerField(db_column='school_id', primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.IntegerField(null=True)),
                ('mbti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.mbti')),
                ('school', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='School_Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.major')),
                ('school', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school')),
            ],
        ),
    ]
