# Generated by Django 3.2.6 on 2021-08-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.mbti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school'),
        ),
    ]
