# Generated by Django 3.2.6 on 2021-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(default='21학번', max_length=4),
        ),
    ]
