# Generated by Django 3.2.6 on 2021-08-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0002_auto_20210815_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='major',
            name='school',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school'),
        ),
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
