# Generated by Django 3.2.6 on 2021-08-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0002_alter_user_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_major',
            name='major',
        ),
        migrations.RemoveField(
            model_name='school_major',
            name='school',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='School_Major',
        ),
    ]
