# Generated by Django 3.2.6 on 2021-08-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0003_auto_20210817_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(default=1, help_text='school ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.BigAutoField(help_text='school ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mbtiapp.school'),
        ),
    ]
