# Generated by Django 3.2.6 on 2021-08-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0004_auto_20210817_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='school',
        ),
    ]
